language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  - "pip install ."
  - "pip install pytest pytest-cov pytest-pep8 coveralls"
script: "py.test"
after_success: "coveralls"
branches:
  only:
    - master
